[package]
name = "decentralized_escrow_service"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "0.1.0"

[dev-dependencies]
soroban-sdk = { version = "0.1.0", features = ["testutils"] }

[features]
default = []
